on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - uses: docker/setup-buildx-action@v1
      - uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v0
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev -q
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:${{ github.sha }}
            us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:latest
          cache-from: type=registry,ref=us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:buildcache
          cache-to: type=registry,ref=us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:buildcache,mode=max
  deploy:
    runs-on: self-hosted
    steps:
      - run: ./kubectl set image deployment/simple-budget simple-budget=us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:latest
