# on:
#   push:
#     branches:
#       - main
# 
# concurrency:
#   group: cd
#   cancel-in-progress: true
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write
#     steps:
#       - uses: actions/checkout@v4
#       - uses: google-github-actions/auth@v1
#         id: auth
#         with:
#           export_environment_variables: false
#           service_account: ${{ secrets.SERVICE_ACCOUNT }}
#           token_format: access_token
#           workload_identity_provider: ${{ secrets.PROVIDER }}
#       - uses: docker/login-action@v3
#         with:
#           registry: us-central1-docker.pkg.dev
#           username: oauth2accesstoken
#           password: ${{ steps.auth.outputs.access_token }}
#       - uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:latest
#           cache-from: type=registry,ref=us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/simple-budget:latest
#           cache-to: type=inline
